<?php

namespace AppBundle\Repository;

/**
 * CondicionivaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CondicionivaRepository extends \Doctrine\ORM\EntityRepository
{
}
