<?php

namespace AppBundle\Repository;

/**
 * HojarutadetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HojarutadetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
