<?php

namespace AppBundle\Repository;

/**
 * HojarutaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HojarutaRepository extends \Doctrine\ORM\EntityRepository
{
}
