<?php

namespace AppBundle\Repository;

/**
 * ImpuestoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImpuestoRepository extends \Doctrine\ORM\EntityRepository
{
}
