<?php

namespace AppBundle\Repository;

/**
 * MovimientostockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientostockRepository extends \Doctrine\ORM\EntityRepository
{
}
