<?php

namespace AppBundle\Repository;

use AppBundle\Entity\GlobalValue;

/**
 * ParametroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParametroRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findPrecioxkilo()
    {
        return $this->createQueryBuilder('t')
        ->andWhere('t.nombre = :nombre')
        ->setParameter('nombre', GlobalValue::PARAMETRO_PRECIO_KILO);
    }
}
