<?php

namespace AppBundle\Repository;

/**
 * PedidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidoRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function cantidadNoVisto()
    {
        return $this->createQueryBuilder('t')
        ->andWhere('t.visto = :visto')
        ->setParameter('visto', false)
        ->select('COUNT(t.visto) as cantidad')
        ->getQuery()
        ->getSingleScalarResult();
    }
}
