<?php

namespace AppBundle\Repository;

/**
 * PedidodetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidodetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
